package ru.mail.polis.metro

enum class Metro(val stationName: String, val branchColor: String) {
    AVTOVO("Автово", "red"),
    ADMIRALTEYSKAYA("Адмиралтейская", "purple"),
    ACADEMIC("Академическая", "red"),
    BALTIC("Балтийская", "red"),
    BUCHAREST("Бухарестская", "purple"),
    VASILEOSTROVSKAYA("Василеостровская", "green"),
    VLADIMIRSKAYA("Владимирская", "green"),
    VOLKOVSKYAYA("Волковская", "purple"),
    VYBORGSKAYA("Выборгская", "red"),
    GORKOVSKAYA("Горьковская", "blue"),
    GOSTINY_DVOR("Гостиный двор", "green"),
    CIVIL_PROSPECT("Гражданский проспект", "red"),
    DEVYATKINO("Девяткино", "red"),
    DOSTOEVSKAYA("Достоевская", "orange"),
    ELIZAROVSKAYA("Елизаровская", "green"),
    STAR("Звёздная", "blue"),
    ZVENIGORODSKAYA("Звенигородская", "purple"),
    KIROVSKY_ZAVOD("Кировский завод", "red"),
    COMMANDANT_PROSPECT("Комендантский проспект", "purple"),
    KRESTOVSKY_ISLAND("Крестовский остров", "purple"),
    KUPCHINO("Купчино", "blue"),
    LADOGA("Ладожская", "orange"),
    LENINSKY_PROSPECT("Ленинский проспект", "red"),
    LESNAYA("Лесная", "red"),
    LIGOVSKY_PROSPECT("Лиговский проспект", "orange"),
    LOMONOSOVSKAYA("Ломоносовская", "green"),
    MAYAKOVSKAYA("Маяковская", "green"),
    INTERNATIONAL("Международная", "purple"),
    MOSCOW("Московская", "blue"),
    MOSCOW_GATES("Московские ворота", "blue"),
    NARVA("Нарвская", "red"),
    NEVSKY_PROSPECT("Невский проспект", "blue"),
    NOVOCHERSSKAYA("Новочеркасская", "orange"),
    OBVODNYI_CHANNEL("Обводный канал", "purple"),
    OBUKHOVO("Обухово", "green"),
    OZERKI("Озерки", "blue"),
    VICTORY_PARK("Парк Победы", "blue"),
    PARNASSUS("Парнас", "blue"),
    PETROGRADSKAYA("Петроградская", "blue"),
    PIONERSKAYA("Пионерская", "blue"),
    ALEXANDER_NEVSKY_PLOSHCHAD_ONE("Площадь Александра Невского 1", "green"),
    ALEXANDER_NEVSKY_PLOSHCHAD_TWO("Площадь Александра Невского 2", "orange"),
    VOSSTANIYA_PLOSHCHAD("Площадь Восстания", "red"),
    LENIN_PLOSHCHAD("Площадь Ленина", "red"),
    COURAGE_PLOSHCHAD("Площадь Мужества", "red"),
    POLYTECHNIC("Политехническая", "red"),
    PRIMORSKAYA("Приморская", "green"),
    PROLETARIAN("Пролетарская", "green"),
    BOLSHEVIKS_PROSPECT("Проспект Большевиков", "orange"),
    VETERANS_PROSPECT("Проспект Ветеранов", "red"),
    EDUCATION_PROSPECT("Проспект Просвещения", "blue"),
    PUSHKINSKAYA("Пушкинская", "green"),
    RYBATSKOE("Рыбацкое", "green"),
    SADOVAYA("Садовая", "purple"),
    SENNAYA_PLOSHCHAD("Сенная площадь", "blue"),
    SPASSKAYA("Спасская", "orange"),
    SPORTIVNAYA("Спортивная", "purple"),
    OLD_VILLAGE("Старая Деревня", "purple"),
    TECHNOLOGY_INSTITYTE_ONE("Технологический институт 1", "red"),
    TECHNOLOGY_INSTITYTE_TWO("Технологический институт 2", "blue"),
    UDELNAYA("Удельная", "blue"),
    DYBENKO_STREE("Улица Дыбенко", "orange"),
    FRUNZENSKAYA("Фрунзенская", "blue"),
    BLACK_RIVER("Чёрная речка", "blue"),
    CHERNYSHEVSKAYA("Чернышевская", "red"),
    CHKALOVSKAYA("Чкаловская", "purple"),
    ELECTROSILA("Электросила", "blue")
}
